apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      # initContainers:
      # - name: init-permissions
      #   image: busybox
      #   command: ['sh', '-c', 'chmod -R 777 /var/lib/grafana']
        # volumeMounts:
        # - name: grafana-storage
        #   mountPath: /var/lib/grafana
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        # resources:
        #   limits:
        #     memory: "1Gi"
        #     cpu: "1000m"
        #   requests: 
        #     memory: 500M
        #     cpu: "500m"
      #   volumeMounts:
      #     - mountPath: /var/lib/grafana
      #       name: grafana-storage
      # volumes:
      #    - name: grafana-storage
      #      persistentVolumeClaim:
      #        claimName: grafana-pvc
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: grafana-pv
#   namespace: monitoring
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/home/node/Documents/grafana"

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: grafana-pvc
#   namespace: monitoring
# spec:
#   volumeName: grafana-pv
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi          